/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BespokeRouteImport } from './routes/bespoke'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BespokeRoute = BespokeRouteImport.update({
  id: '/bespoke',
  path: '/bespoke',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bespoke': typeof BespokeRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/experience': typeof ExperienceRoute
  '/journal': typeof JournalRoute
  '/orders': typeof OrdersRoute
  '/our-story': typeof OurStoryRoute
  '/stores': typeof StoresRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bespoke': typeof BespokeRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/experience': typeof ExperienceRoute
  '/journal': typeof JournalRoute
  '/orders': typeof OrdersRoute
  '/our-story': typeof OurStoryRoute
  '/stores': typeof StoresRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bespoke': typeof BespokeRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/experience': typeof ExperienceRoute
  '/journal': typeof JournalRoute
  '/orders': typeof OrdersRoute
  '/our-story': typeof OurStoryRoute
  '/stores': typeof StoresRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bespoke'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/experience'
    | '/journal'
    | '/orders'
    | '/our-story'
    | '/stores'
    | '/wishlist'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bespoke'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/experience'
    | '/journal'
    | '/orders'
    | '/our-story'
    | '/stores'
    | '/wishlist'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/bespoke'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/experience'
    | '/journal'
    | '/orders'
    | '/our-story'
    | '/stores'
    | '/wishlist'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BespokeRoute: typeof BespokeRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionsRoute: typeof CollectionsRoute
  ExperienceRoute: typeof ExperienceRoute
  JournalRoute: typeof JournalRoute
  OrdersRoute: typeof OrdersRoute
  OurStoryRoute: typeof OurStoryRoute
  StoresRoute: typeof StoresRoute
  WishlistRoute: typeof WishlistRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bespoke': {
      id: '/bespoke'
      path: '/bespoke'
      fullPath: '/bespoke'
      preLoaderRoute: typeof BespokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BespokeRoute: BespokeRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionsRoute: CollectionsRoute,
  ExperienceRoute: ExperienceRoute,
  JournalRoute: JournalRoute,
  OrdersRoute: OrdersRoute,
  OurStoryRoute: OurStoryRoute,
  StoresRoute: StoresRoute,
  WishlistRoute: WishlistRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
